// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package proto;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<proto.StudentResponse> 
      getStudentResponseList();
  /**
   * <code>repeated .proto.StudentResponse studentResponse = 1;</code>
   */
  proto.StudentResponse getStudentResponse(int index);
  /**
   * <code>repeated .proto.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <code>repeated .proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends proto.StudentResponseOrBuilder> 
      getStudentResponseOrBuilderList();
  /**
   * <code>repeated .proto.StudentResponse studentResponse = 1;</code>
   */
  proto.StudentResponseOrBuilder getStudentResponseOrBuilder(
      int index);
}
