// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package proto;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_MyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_StudentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_StudentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_StudentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_StudentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_StudentResponseList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_StudentResponseList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_StreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_StreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_StreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_StreamResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rStudent.proto\022\005proto\"\035\n\tMyRequest\022\020\n\010u" +
      "sername\030\001 \001(\t\"\036\n\nMyResponse\022\020\n\010realname\030" +
      "\002 \001(\t\"\035\n\016StudentRequest\022\013\n\003age\030\001 \001(\005\":\n\017" +
      "StudentResponse\022\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001" +
      "(\005\022\014\n\004city\030\003 \001(\t\"F\n\023StudentResponseList\022" +
      "/\n\017studentResponse\030\001 \003(\0132\026.proto.Student" +
      "Response\"%\n\rStreamRequest\022\024\n\014request_inf" +
      "o\030\001 \001(\t\"\'\n\016StreamResponse\022\025\n\rresponse_in" +
      "fo\030\001 \001(\t2\246\002\n\016StudentService\022>\n\025GetRealNa" +
      "meByUsername\022\020.proto.MyRequest\032\021.proto.M" +
      "yResponse\"\000\022E\n\020GetStudentsByAge\022\025.proto." +
      "StudentRequest\032\026.proto.StudentResponse\"\000" +
      "0\001\022P\n\027GetStudentWrapperByAges\022\025.proto.St" +
      "udentRequest\032\032.proto.StudentResponseList" +
      "\"\000(\001\022;\n\006BiTalk\022\024.proto.StreamRequest\032\025.p" +
      "roto.StreamResponse\"\000(\0010\001B\027\n\005protoB\014Stud" +
      "entProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_MyRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_proto_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_MyResponse_descriptor,
        new java.lang.String[] { "Realname", });
    internal_static_proto_StudentRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_StudentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_StudentRequest_descriptor,
        new java.lang.String[] { "Age", });
    internal_static_proto_StudentResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_proto_StudentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_StudentResponse_descriptor,
        new java.lang.String[] { "Name", "Age", "City", });
    internal_static_proto_StudentResponseList_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_proto_StudentResponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_StudentResponseList_descriptor,
        new java.lang.String[] { "StudentResponse", });
    internal_static_proto_StreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_proto_StreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_StreamRequest_descriptor,
        new java.lang.String[] { "RequestInfo", });
    internal_static_proto_StreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_proto_StreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_StreamResponse_descriptor,
        new java.lang.String[] { "ResponseInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
